# Generated by Django 4.2.2 on 2023-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='ststic/img/menu_item/default_image', upload_to='item_menu/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
